-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  module_code character varying,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.catalogos_schema (
  negocio_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  schema_data jsonb NOT NULL,
  CONSTRAINT catalogos_schema_pkey PRIMARY KEY (negocio_id),
  CONSTRAINT catalogos_schema_negocio_id_fkey FOREIGN KEY (negocio_id) REFERENCES public.negocios(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  legal_name character varying,
  tax_id character varying,
  address text,
  phone character varying,
  email character varying,
  website character varying,
  logo_url text,
  is_active boolean DEFAULT true,
  fiscal_year_start integer DEFAULT 1,
  currency_code character varying DEFAULT 'USD'::character varying,
  timezone character varying DEFAULT 'America/Mexico_City'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.fin_account_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  normal_balance character varying NOT NULL DEFAULT 'DEBIT'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_account_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fin_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  account_type_id uuid NOT NULL,
  parent_account_id uuid,
  is_active boolean DEFAULT true,
  is_detail boolean DEFAULT false,
  requires_cost_center boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT fin_accounts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT fin_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fin_accounts_account_type_id_fkey FOREIGN KEY (account_type_id) REFERENCES public.fin_account_types(id),
  CONSTRAINT fin_accounts_parent_account_id_fkey FOREIGN KEY (parent_account_id) REFERENCES public.fin_accounts(id)
);
CREATE TABLE public.fin_closing_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  closing_date date NOT NULL,
  closing_type character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying,
  closing_journal_entry_id uuid,
  created_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_closing_entries_pkey PRIMARY KEY (id),
  CONSTRAINT fin_closing_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT fin_closing_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fin_closing_entries_closing_journal_entry_id_fkey FOREIGN KEY (closing_journal_entry_id) REFERENCES public.fin_journal_entries(id),
  CONSTRAINT fin_closing_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fin_closing_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.fin_cost_centers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_cost_centers_pkey PRIMARY KEY (id),
  CONSTRAINT fin_cost_centers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT fin_cost_centers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.fin_currency_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  from_currency character varying NOT NULL,
  to_currency character varying NOT NULL,
  rate numeric NOT NULL,
  rate_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_currency_rates_pkey PRIMARY KEY (id),
  CONSTRAINT fin_currency_rates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.fin_journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  entry_number character varying NOT NULL,
  entry_date date NOT NULL,
  posting_date date NOT NULL,
  description text,
  reference character varying,
  journal_type character varying NOT NULL DEFAULT 'GENERAL'::character varying,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying,
  total_debit numeric DEFAULT 0,
  total_credit numeric DEFAULT 0,
  created_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT fin_journal_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT fin_journal_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fin_journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fin_journal_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.fin_journal_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_entry_id uuid NOT NULL,
  line_number integer NOT NULL,
  account_id uuid NOT NULL,
  cost_center_id uuid,
  debit_amount numeric DEFAULT 0,
  credit_amount numeric DEFAULT 0,
  currency_code character varying DEFAULT 'USD'::character varying,
  exchange_rate numeric DEFAULT 1,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fin_journal_lines_pkey PRIMARY KEY (id),
  CONSTRAINT fin_journal_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.fin_journal_entries(id),
  CONSTRAINT fin_journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.fin_accounts(id),
  CONSTRAINT fin_journal_lines_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.fin_cost_centers(id)
);
CREATE TABLE public.inventario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  negocio_id uuid NOT NULL,
  item_data jsonb NOT NULL,
  CONSTRAINT inventario_pkey PRIMARY KEY (id),
  CONSTRAINT inventario_negocio_id_fkey FOREIGN KEY (negocio_id) REFERENCES public.negocios(id)
);
CREATE TABLE public.module_dependencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid NOT NULL,
  depends_on_module_id uuid NOT NULL,
  is_required boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT module_dependencies_pkey PRIMARY KEY (id),
  CONSTRAINT module_dependencies_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id),
  CONSTRAINT module_dependencies_depends_on_module_id_fkey FOREIGN KEY (depends_on_module_id) REFERENCES public.modules(id)
);
CREATE TABLE public.modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category character varying NOT NULL,
  icon character varying,
  color character varying,
  version character varying DEFAULT '1.0.0'::character varying,
  route_path character varying,
  is_core boolean DEFAULT false,
  is_available boolean DEFAULT true,
  price_monthly numeric DEFAULT 0,
  requires_storage_mb integer DEFAULT 100,
  sort_order integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.negocios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  owner_id text NOT NULL,
  CONSTRAINT negocios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  price_monthly numeric NOT NULL,
  price_yearly numeric,
  max_users integer NOT NULL DEFAULT 5,
  max_companies integer NOT NULL DEFAULT 1,
  storage_gb integer NOT NULL DEFAULT 10,
  features jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  opportunity_id uuid,
  contact_id uuid,
  activity_type character varying NOT NULL,
  subject character varying NOT NULL,
  description text,
  activity_date timestamp without time zone NOT NULL,
  duration_minutes integer,
  assigned_to uuid NOT NULL,
  status character varying DEFAULT 'PENDING'::character varying,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_activities_pkey PRIMARY KEY (id),
  CONSTRAINT sales_activities_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_activities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.sales_opportunities(id),
  CONSTRAINT sales_activities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.sales_contacts(id),
  CONSTRAINT sales_activities_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT sales_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid,
  name character varying NOT NULL,
  legal_name character varying,
  tax_id character varying,
  industry character varying,
  website character varying,
  phone character varying,
  email character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  employee_count integer,
  annual_revenue numeric,
  assigned_to uuid,
  tags ARRAY DEFAULT '{}'::text[],
  is_customer boolean DEFAULT false,
  is_prospect boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_companies_pkey PRIMARY KEY (id),
  CONSTRAINT sales_companies_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT sales_companies_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  sales_company_id uuid,
  title character varying,
  first_name character varying NOT NULL,
  last_name character varying,
  email character varying,
  phone character varying,
  mobile character varying,
  position character varying,
  department character varying,
  assigned_to uuid,
  tags ARRAY DEFAULT '{}'::text[],
  is_primary_contact boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT sales_contacts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_contacts_sales_company_id_fkey FOREIGN KEY (sales_company_id) REFERENCES public.sales_companies(id),
  CONSTRAINT sales_contacts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_opportunities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  pipeline_id uuid NOT NULL,
  stage_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  sales_company_id uuid NOT NULL,
  primary_contact_id uuid,
  amount numeric,
  expected_close_date date,
  actual_close_date date,
  probability_percent integer DEFAULT 0,
  source character varying,
  assigned_to uuid,
  is_closed boolean DEFAULT false,
  is_won boolean DEFAULT false,
  reason_lost character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT sales_opportunities_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_opportunities_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.sales_pipelines(id),
  CONSTRAINT sales_opportunities_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.sales_stages(id),
  CONSTRAINT sales_opportunities_sales_company_id_fkey FOREIGN KEY (sales_company_id) REFERENCES public.sales_companies(id),
  CONSTRAINT sales_opportunities_primary_contact_id_fkey FOREIGN KEY (primary_contact_id) REFERENCES public.sales_contacts(id),
  CONSTRAINT sales_opportunities_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_order_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL,
  line_number integer NOT NULL,
  product_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric DEFAULT 0,
  line_amount numeric NOT NULL,
  tax_percent numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_lines_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id)
);
CREATE TABLE public.sales_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  opportunity_id uuid,
  order_number character varying NOT NULL,
  order_date date NOT NULL,
  customer_id uuid,
  billing_address text,
  shipping_address text,
  status character varying DEFAULT 'PENDING'::character varying,
  total_amount numeric DEFAULT 0,
  discount_percent numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  net_amount numeric DEFAULT 0,
  currency_code character varying DEFAULT 'USD'::character varying,
  notes text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sales_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT sales_orders_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.sales_opportunities(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.sales_companies(id),
  CONSTRAINT sales_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_pipelines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  currency_code character varying DEFAULT 'USD'::character varying,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_pipelines_pkey PRIMARY KEY (id),
  CONSTRAINT sales_pipelines_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.sales_stages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pipeline_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  probability_percent integer DEFAULT 0,
  is_closed boolean DEFAULT false,
  is_won boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_stages_pkey PRIMARY KEY (id),
  CONSTRAINT sales_stages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.sales_pipelines(id)
);
CREATE TABLE public.scm_po_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  line_number integer NOT NULL,
  product_id uuid NOT NULL,
  quantity_ordered numeric NOT NULL,
  quantity_received numeric DEFAULT 0,
  unit_price numeric NOT NULL,
  line_amount numeric NOT NULL,
  tax_percent numeric DEFAULT 0,
  expected_delivery_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  variant_id uuid,
  tenant_id uuid,
  CONSTRAINT scm_po_lines_pkey PRIMARY KEY (id),
  CONSTRAINT scm_po_lines_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.scm_purchase_orders(id),
  CONSTRAINT scm_po_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.scm_products(id),
  CONSTRAINT scm_po_lines_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.scm_product_variants(id),
  CONSTRAINT scm_po_lines_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.scm_product_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  parent_category_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scm_product_categories_pkey PRIMARY KEY (id),
  CONSTRAINT scm_product_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_product_categories_parent_category_id_fkey FOREIGN KEY (parent_category_id) REFERENCES public.scm_product_categories(id)
);
CREATE TABLE public.scm_product_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  media_type character varying NOT NULL DEFAULT 'image'::character varying,
  file_url text NOT NULL,
  description character varying,
  is_primary boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scm_product_media_pkey PRIMARY KEY (id),
  CONSTRAINT scm_product_media_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.scm_products(id)
);
CREATE TABLE public.scm_product_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  variant_sku character varying,
  attribute_value character varying NOT NULL,
  attribute_name character varying DEFAULT 'Talla'::character varying,
  is_active boolean DEFAULT true,
  price_adjustment numeric DEFAULT 0,
  cost_adjustment numeric DEFAULT 0,
  sku text,
  CONSTRAINT scm_product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT scm_product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.scm_products(id),
  CONSTRAINT scm_product_variants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_product_variants_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.scm_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  sku character varying NOT NULL,
  barcode character varying,
  name character varying NOT NULL,
  description text,
  category_id uuid,
  unit_type character varying DEFAULT 'PIECE'::character varying,
  purchase_price numeric,
  sale_price numeric,
  cost_price numeric,
  reorder_point integer DEFAULT 0,
  reorder_quantity integer DEFAULT 0,
  lead_time_days integer DEFAULT 0,
  is_active boolean DEFAULT true,
  requires_serial_number boolean DEFAULT false,
  requires_batch_tracking boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_manufacturable boolean DEFAULT false,
  image_url text,
  size_config jsonb,
  company_id uuid,
  CONSTRAINT scm_products_pkey PRIMARY KEY (id),
  CONSTRAINT scm_products_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.scm_product_categories(id)
);
CREATE TABLE public.scm_purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  po_number character varying NOT NULL,
  po_date date NOT NULL,
  supplier_id uuid NOT NULL,
  expected_delivery_date date,
  status character varying DEFAULT 'DRAFT'::character varying,
  total_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  freight_amount numeric DEFAULT 0,
  net_amount numeric DEFAULT 0,
  currency_code character varying DEFAULT 'USD'::character varying,
  notes text,
  created_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  warehouse_id uuid,
  CONSTRAINT scm_purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT scm_purchase_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_purchase_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT scm_purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.scm_suppliers(id),
  CONSTRAINT scm_purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT scm_purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT scm_purchase_orders_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.scm_warehouses(id)
);
CREATE TABLE public.scm_stock_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  old_product_id uuid,
  warehouse_id uuid NOT NULL,
  quantity_on_hand numeric DEFAULT 0,
  quantity_available numeric DEFAULT 0,
  quantity_reserved numeric DEFAULT 0,
  quantity_in_transit numeric DEFAULT 0,
  last_counted_at timestamp with time zone,
  last_movement_date date DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  variant_id uuid,
  company_id uuid,
  CONSTRAINT scm_stock_levels_pkey PRIMARY KEY (id),
  CONSTRAINT scm_stock_levels_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_stock_levels_product_id_fkey FOREIGN KEY (old_product_id) REFERENCES public.scm_products(id),
  CONSTRAINT scm_stock_levels_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.scm_warehouses(id),
  CONSTRAINT scm_stock_levels_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.scm_product_variants(id)
);
CREATE TABLE public.scm_stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  old_product_id_mvt uuid,
  warehouse_id uuid NOT NULL,
  movement_type character varying NOT NULL,
  quantity numeric NOT NULL,
  unit_cost numeric,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  movement_date date NOT NULL,
  notes text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  variant_id uuid,
  company_id uuid,
  CONSTRAINT scm_stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT scm_stock_movements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_stock_movements_product_id_fkey FOREIGN KEY (old_product_id_mvt) REFERENCES public.scm_products(id),
  CONSTRAINT scm_stock_movements_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.scm_warehouses(id),
  CONSTRAINT scm_stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT scm_stock_movements_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.scm_product_variants(id)
);
CREATE TABLE public.scm_suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  legal_name character varying,
  tax_id character varying,
  contact_name character varying,
  email character varying,
  phone character varying,
  mobile character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  payment_terms character varying,
  is_active boolean DEFAULT true,
  rating integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  payment_terms_days integer DEFAULT 0,
  CONSTRAINT scm_suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT scm_suppliers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_suppliers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.scm_warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  address text,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scm_warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT scm_warehouses_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT scm_warehouses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.sucursales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  negocio_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['Punto de Venta'::text, 'Bodega'::text, 'Oficina'::text])),
  CONSTRAINT sucursales_pkey PRIMARY KEY (id),
  CONSTRAINT sucursales_negocio_id_fkey FOREIGN KEY (negocio_id) REFERENCES public.negocios(id)
);
CREATE TABLE public.tenant_licenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  module_id uuid NOT NULL,
  subscription_id uuid,
  is_active boolean DEFAULT true,
  installed_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  last_used_at timestamp with time zone,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenant_licenses_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_licenses_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_licenses_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id),
  CONSTRAINT tenant_licenses_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.tenant_subscriptions(id)
);
CREATE TABLE public.tenant_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  started_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  auto_renew boolean DEFAULT true,
  payment_method character varying,
  payment_method_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT tenant_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_subscriptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug character varying NOT NULL UNIQUE CHECK (slug::text ~ '^[a-z0-9-]+$'::text),
  name character varying NOT NULL,
  legal_name character varying,
  tax_id character varying,
  industry character varying DEFAULT 'manufacturing'::character varying,
  logo_url text,
  primary_color character varying DEFAULT '#0ea5e9'::character varying CHECK (primary_color::text ~ '^#[0-9a-f]{6}$'::text),
  is_active boolean DEFAULT true,
  subscription_status character varying DEFAULT 'trial'::character varying,
  trial_ends_at timestamp with time zone DEFAULT (now() + '14 days'::interval),
  max_users integer DEFAULT 5,
  max_companies integer DEFAULT 1,
  storage_gb integer DEFAULT 10,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT tenants_pkey PRIMARY KEY (id),
  CONSTRAINT tenants_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.users_tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'user'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_tenants_pkey PRIMARY KEY (id),
  CONSTRAINT users_tenants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT users_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);